engineclub/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.base import TemplateView

from contact_form.views import contact_form
from ecutils.forms import SCContactForm

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'home.views.index', name='index'),
    url(r'^home/$', 'home.views.home', name='home'),
    (r'^acct/', include('youraliss.urls')),
    (r'^api/', include('resources.api_urls')),
    (r'^analytics/', include('analytics.urls')),
    (r'^cab/', include('enginecab.urls')),
    (r'^depot/', include('resources.urls')),
    (r'^users/', include('accounts.urls')),
    (r'^stories/', include('stories.urls')),
    url(r'^search/$', 'resources.views.resource_find', name='search'),

    url(r'^contact/$', contact_form, { 'form_class': SCContactForm }, name='contact'),
    url(r'^contact/sent/$', TemplateView.as_view(template_name='contact_form/contact_form_sent.html'),
        name='contact_form_sent'),

    (r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^logout/$', 'logout', name='logout') ,
    url(r'^accounts/login/', 'login', name='login'),
    url(r'^password_reset/$','password_reset', name='password_reset'),
    (r'^password_reset/done/$', 'password_reset_done' ),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'password_reset_confirm'),
    (r'^reset/done/$', 'password_reset_complete'),
    url(r'^accounts/password_change/$', 'password_change', name='password_change'),
    (r'^accounts/password_change/done/$', 'password_change_done' ),
)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
  urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$',
      'django.views.static.serve',
      {'document_root': settings.MEDIA_ROOT}
    ),
  )

engineclub/apps/engine/depot/forms.py
from django import forms
# import floppyforms as forms

from depot.models import Resource, Curation, Location
from depot.search import find_by_place_or_kwords
from ecutils.forms import DocumentForm, PlainForm, CSVTextInput, clean_csvtextinput
from firebox.views import *
from issues.models import SEVERITY_LOW, SEVERITY_MEDIUM, SEVERITY_HIGH, SEVERITY_CRITICAL

from mongoengine.queryset import DoesNotExist

from datetime import datetime

class FormHasNoInstanceException(Exception):
    pass

class FindResourceForm(PlainForm):
    
    post_code = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-text expand'}), label='Location', help_text='enter a post code or a place name', required=False)
    kwords = forms.CharField(widget=CSVTextInput(attrs={'class': 'input-text expand'}), label='Search text', help_text='comma separated text (spaces OK)', required=False)
    events_only = forms.BooleanField(required=False)
    boost_location = forms.CharField(widget=forms.HiddenInput, required=False)

    def __init__(self, *args, **kwargs):
        self.locations = []
        self.results = []
        self.centre = None
        if 'label_suffix' not in kwargs:
            kwargs['label_suffix'] = ''
        super(FindResourceForm, self).__init__(*args, **kwargs)

    def clean_boost_location(self):
        """docstring for clean_boost_location"""
        data = self.cleaned_data['boost_location']
        if data.isdigit():
            data = int(data)
            return data if data <= 100 else 100
        return ''

    def clean(self):
        # if errors in data, cleaned_data may be wiped, and/or fields not available
        cleaned_data = self.cleaned_data
        data = cleaned_data.get('post_code', '').strip()
        kwords = cleaned_data.get('kwords', '').strip()
        boost_location = cleaned_data.get('boost_location', '') or settings.SOLR_LOC_BOOST_DEFAULT
        event = cleaned_data.get('events_only')

        if not(data or kwords):
            raise forms.ValidationError("Please enter a location and/or some text and try again.")

        loc, self.results = find_by_place_or_kwords(data, kwords, boost_location, event='*' if event else None)
        if loc:
            self.centre = {'name': data, 'location': loc }
        elif data:
            raise forms.ValidationError("Could not find a location from what you've typed- try again?")
            
        return cleaned_data

class ShortResourceForm(DocumentForm):

    uri = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-text expand'}),required=False)
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-text expand'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'input-text expand'}), required=False)
    tags = forms.CharField(widget=CSVTextInput(attrs={'class': 'input-text expand'}), label='Tags (keywords)', help_text='separate words or phrases with commas', required=False)

    def clean_tags(self):
        return clean_csvtextinput(self.cleaned_data['tags'])

    def clean_uri(self):
        data = self.cleaned_data['uri']
        if data:
            try:
                if self.instance:
                    # id__not=instance.id throws an error, this works
                    check = Resource.objects(id__not__in=[self.instance.id], uri=data)
                else:
                    check = Resource.objects(uri=data)
                if check.count() > 0:
                    raise forms.ValidationError("There is already an item with this uri")
            except DoesNotExist:
                pass
        return data
    
class EventForm(DocumentForm):
    
    from ecutils.fields import JqSplitDateTimeField
    from ecutils.widgets import JqSplitDateTimeWidget

    widget_attrs={'class': 'datetimepicker', 'date_class':'datepicker input-text','time_class':'timepicker input-text'}

    start = JqSplitDateTimeField(required=False,
        widget=JqSplitDateTimeWidget(attrs=widget_attrs.copy(), date_format='%d/%m/%Y'))
    end = JqSplitDateTimeField(required=False, 
        widget=JqSplitDateTimeWidget(attrs=widget_attrs, date_format='%d/%m/%Y'))

    def clean(self):
        start = self.cleaned_data.get('start', None)
        end = self.cleaned_data.get('end', None)
        now = datetime.now()
        if end:
            if start:
                if end < start:
                    raise forms.ValidationError('The start date must be earlier than the finish date.')
            else:
                raise forms.ValidationError('Please enter a start date.')
            if end < now:
                raise forms.ValidationError('The end date must be in the future.')
        elif start:
            if start < now:
                raise forms.ValidationError('The start date must be in the future.')

        return self.cleaned_data

class LocationUpdateForm(DocumentForm):
    # REPLACE
    new_location = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-text expand'}), required=False)
    # new_location = forms.CharField(widget=CSVTextInput, required=False, help_text='comma separated text (spaces OK)')
    locations = None

    def clean_new_location(self):
        data = self.cleaned_data['new_location']
        loc_ids = data.split(',')
        locs = list(Location.objects(id__in=loc_ids))
        new_locs = [l for l in loc_ids if l not in [loc.id for loc in locs]]
        new_locs_errors = []
        for new_loc in new_locs:
            loc = Location.create_from(new_loc)
            if loc:
                locs.append(loc)
            else:
                new_locs_errors.append(new_loc)
        self.locations = locs
        if new_locs_errors:
            raise forms.ValidationError('Could not find these locations: %s' % ', '.join(new_locs_errors))
        return data

class MetadataForm(DocumentForm):
    """docstring for MetadataForm"""
    last_modified = forms.DateField(required=False)
    shelflife = forms.CharField(required=False)
    author = forms.CharField(required=False)
    status = forms.CharField(required=False)
    admin_note = forms.CharField(widget=forms.Textarea, required=False)

class TagsForm(DocumentForm):
    """docstring for TagsForm"""
    tags = forms.CharField(widget=CSVTextInput, label='Tags (keywords)', help_text='separate words or phrases with commas', required=False)

    def clean_tags(self):
        return clean_csvtextinput(self.cleaned_data['tags'])
    
class ShelflifeForm(DocumentForm):
    """docstring for ShelflifeForm"""
    # dummy = forms.CharField(required=False)
    pass
    
class CurationForm(DocumentForm):
    
    outcome = forms.CharField(widget=forms.HiddenInput)

    tags = forms.CharField(widget=CSVTextInput(attrs={'class': 'input-text expand'}), help_text='comma separated tags (spaces OK)', required=False)
    note = forms.CharField(widget=forms.Textarea(attrs={'class': 'input-text expand'}), required=False)
    # data = forms.CharField(widget=forms.Textarea, required=False)
    
    def clean_tags(self):
        return clean_csvtextinput(self.cleaned_data['tags'])

REPORT_CHOICES=(
    (SEVERITY_LOW, 'Not serious- a spelling mistake or some other small correction'), 
    (SEVERITY_MEDIUM, 'Quite serious- something wrong, misleading, or should be checked'), 
    (SEVERITY_HIGH, 'Serious- content that might not suitable for ALISS'),
    (SEVERITY_CRITICAL, 'Very serious- content that is dangerous or offensive')
    )

class ResourceReportForm(PlainForm):
    severity = forms.ChoiceField(
        widget= forms.RadioSelect,
        choices=REPORT_CHOICES,
        label="How serious is this?")
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'input-text large'}))

engineclub/apps/engine/resources/templates/depot/curation_detail.html
{% extends "depot/resource_base.html" %}
{% load markup utils accounts_tags %}
{% load url from future %}

{% block title %}Curation{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumbs">
    <li><a href="{% url 'resource' resource.id %}">Resource</a></li>
    <li class="current"><a href="#">Edit</a></li>
</ul>
{% endblock %}

{% block content %}

<dl class="sub-nav">
    <dt>Actions:</dt>
    {% if user|can_edit:object %}
        <dd><a href="{% url 'curation_edit' resource.id index %}">edit curation</a></dd>
    {% endif %}
    {% if user|can_delete:object %}
        <dd><a href="{% url 'curation_remove' resource.id index %}">delete curation</a></dd>
    {% endif %}
</dl>

<h1>Curation for {{ resource.title }}</h1>

<div class="group">
{% if object.note or object.data %}
    <table class="metadata owned-data">
    <tr><th>note</th><td>{{ object.note|textile|default:' ' }}</td></tr>

    {% for key, value in object.data.items %}
    <tr><th>{{ key }}</th><td>{{ value|textile }}</td></tr>
    {% endfor %}
    </table>
{% else %}
    <p class="resource-description">No additional content in this curation.</p>
{% endif %}
</div>

<div class="group">
<table class="metadata">
<tr><th>owner</th><td><a href="{% url 'accounts_detail' object.owner.id %}">{{ object.owner.name }}</a></td></tr>
<tr><th>last changes</th><td>{{ object.item_metadata.author }}, {{ object.item_metadata.last_modified }}</td></tr>
<tr><th>tags</th><td>{{ object.tags|join:", " }}</td></tr>
</table>
</div>


{% endblock %}

engineclub/apps/engine/resources/templates/depot/curation_edit.html
{% extends "depot/resource_base.html" %}
{% load utils %}
{% load url from future %}

{% block title %}{% if new %}Add curation{% else %}Edit curation{% endif %}{% endblock %}

{% block content %}

<style type="text/css">
.metadata li{
    clear: none;
    width: 50%;
}
.metadata textarea{
    height: 75px;
}
</style>
{% if new %}<h1>Add curation</h1>{% else %}<h1>Edit curation</h1>{% endif %}

<h2>{{ resource.title }}</h2>

<form class="nice form" action=".?next={{ next }}" method="POST">{% csrf_token %}
    <fieldset>
        <legend><span>Curation details:</span></legend>
         {{ form.as_plain }}
    </fieldset>
    <fieldset class="metadata">
        <legend><span>Curation Metadata:</span></legend>
        <ol>
             {{ meta_form.as_ul }}
        </ol>
    </fieldset>
     <fieldset class="submit">
        <input type="submit" name="result" value="Save item">
        <input type="submit" name="result" value="Cancel">
    </fieldset>
</form>

{% endblock %}

{% block script-extra %}
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/base/jquery-ui.css" type="text/css" rel="stylesheet">
<link href="/static/css/token-input-aliss.css" type="text/css" rel="stylesheet">

 <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript"></script>
<script src="/static/js/jquery.tokeninput.js" type="text/javascript"></script>
{% endblock script-extra %}
{% block document-ready %}

$('#id_tags').tokenInput('{% url 'resources.api_handlers.tags' %}', {
    minChars: 3,
    onResult: function (results) {
        var typedValue = $('#token-input-id_tags').val();
        var r = [{id: typedValue, name: typedValue + ' (new)'}];
        $.each(results.data, function (i, item) {
            r.push({id: item, name: item});
        });
        return r;
    },
    prePopulate: [{% for t in object.tags %}{id: "{{ t|safe }}", name: "{{ t|safe }}"}{% if not forloop.last %},{% endif %}{% endfor %}],
    queryParam: 'match',
    theme: 'aliss'
});

{% endblock document-ready %}

engineclub/apps/engine/resources/templates/depot/curations_for_group.html
{% extends "depot/resource_base.html" %}
{% load markup utils depot_tags %}
{% load url from future %}

{% block title %}Curations for {{ object.name }}{% endblock %}

{% block content %}

<p>
    <a href="{% url 'group' object.id %}">back to group</a>
</p>

<h1>Latest curations for {{ object.name }}</h1>

<div id="results">
        
    <ol class="resource-listing">
    {% for resource in curations %}
        <li><p class="resource-listing-title"><a href="{% url 'resource' resource.id %}">{{ resource.title }}</a></p>

            {% if resource.locations %}
                <ol>
                    {% for loc in resource.locations %}
                        <li class="resource-listing-locs">{{ loc }}</li>
                    {% endfor %}
                </ol>
            {% endif %}
            {% if resource.event_start %}
                <ol><li class="resource-listing-locs">event: {{ resource|idx_event_date }}</li></ol>
            {% endif %}


            <p>{{ resource.description|truncatewords:30 }}</p>
            <p class="resource-listing-meta">
                <a class="resource-url" href="{% url 'resource' resource.id %}">more details...</a>
                {% if resource.uri %} |
                    <a href="{{ resource.uri }}">external site...</a>
                {% endif %}
            </p>
<!-- 
-->
        </li>
    {% empty %}
        <li>no results found</li>
    {% endfor %}
    </ol>

</div>


{% endblock %}

engineclub/apps/engine/resources/templates/depot/curations_for_group_embed.html
{% load url from future %}
<html>
<head>
<style>
body  {
    font-size: 0.8em;
    color: #404040;
    font-family: "Trebuchet MS", Trebuchet, Verdana, Arial, Helvetica, sans-serif;
    background-color: #eae5dd;
    margin: 0;
    padding:6px;
}

.gig-title  {
    font-size: 0.9em;
    font-weight: bold;
    color: #d00;
}
.gig-info  {
    font-size: 0.9em;
    color: #33d;
    margin-left: 16px;
    
}
</style>

</head>
<body>
{% load markup %}
<h1>Resources collected by {{ object.name }}</h1>

<div id="results">
        
    <ol class="resource-listing">
    {% for resource in curations %}
        <li><p class="resource-listing-title"><a href="{% url 'resource' resource.id %}">{{ resource.title }}</a></p>

            {% if resource.locations %}
                <ol>
                    {% for loc in resource.locations %}
                        <li class="resource-listing-locs">{{ loc }}</li>
                    {% endfor %}
                </ol>
            {% endif %}

            <p>{{ resource.description|truncatewords:30 }}</p>
            <p class="resource-listing-meta">
                <a class="resource-url" href="{% url 'resource' resource.id %} target="_top"">more details...</a>
                {% if resource.uri %} |
                    <a href="{{ resource.uri }}">external site...</a>
                {% endif %}
            </p>
<!-- 
-->
        </li>
    {% empty %}
        <li>no results found</li>
    {% endfor %}
    </ol>

</div>


</body>
</html>

engineclub/apps/engine/resources/templates/depot/resource_base.html
{% extends "base_tabbed.html" %}

{% block body_class %}resource{% endblock %}

{% block resource-tab %}active{% endblock resource-tab %}

engineclub/apps/engine/resources/templates/depot/resource_edit.html
{% extends template_info.base %}
{% load utils %}
{% load url from future %}

{% block title %}edit resource{% endblock %}

{% block breadcrumbs %}
{% if object %}
    <ul class="breadcrumbs">
        <li><a href="{% url 'resource' object.id  %}">Resource</a></li>
        <li class="current"><a href="#">Edit</a></li>
    </ul>
{% endif %}
{% endblock %}

{% block content %}

{% if not template_info.popup %}<h1>{% if object %}Edit{% else %}Add new{% endif %} item</h1>{% endif %}

<form class="nice form" id="main-form" action="." method="POST">{% csrf_token %}
    <fieldset>
        <legend><span>Resource details:</span></legend>
        {{ resourceform.as_plain }}
    </fieldset>
    {% if tagsform %}
        <fieldset>
            {{ tagsform.as_plain }}
        </fieldset>
    {% endif %}
    
    {% if locationform %}
        <fieldset>
            <legend><span>Locations:</span></legend>
            {{ locationform.as_plain }}
        </fieldset>
    {% endif %}
    {% if eventform %}
        <fieldset>
            <legend><span>Event details:</span></legend>
             {{ eventform.as_plain }}
        </fieldset>
    {% endif %}
    {% if shelflifeform %}
        <fieldset>
            <legend><span>Shelf life:</span></legend>
             {{ shelflifeform.as_plain }}
        </fieldset>
    {% endif %}
     <fieldset class="submit">
        <input type="hidden" name="popup" value="{{ template_info.popup }}">
        <input type="submit" name="result" value="Save item">
        <input type="submit" name="result" value="Cancel">
    </fieldset>
</form>

{% if user.is_superuser %}
    <p>{{ debug_info }}</p> 
    
{% endif %}
{% endblock %}

{% block script-extra %}
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/base/jquery-ui.css" type="text/css" rel="stylesheet">
<link href="/static/css/token-input-aliss.css" type="text/css" rel="stylesheet">

 <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript"></script>
<script src="/static/js/jquery.tokeninput.js" type="text/javascript"></script>
{% endblock script-extra %}
{% block document-ready %}
$('#new_location_submit').replaceWith('<a href="#" class="add-link" id="new_location_link">add location</a>');
//$('#new_location_link').click(function() {alert('blah');});
$('#new_location_link').click(function() {$('#main-form').submit();});
$(".datepicker").datepicker({ dateFormat: 'dd/mm/yy' });

$('#id_tags').tokenInput('{% url 'resources.api_handlers.tags' %}', {
    minChars: 3,
    onResult: function (results) {
        var typedValue = $('#token-input-id_tags').val();
        var r = [{id: typedValue, name: typedValue + ' (new)'}];
        $.each(results.data, function (i, item) {
            r.push({id: item, name: item});
        });
        return r;
    },
    prePopulate: [{% for t in object.tags %}{id: "{{ t|safe }}", name: "{{ t|safe }}"}{% if not forloop.last %},{% endif %}{% endfor %}],
    queryParam: 'match',
    theme: 'aliss'
});
{% if locationform %}
    $('#id_new_location').tokenInput('{% url 'resources.api_handlers.locations' %}', {
        minChars: 3,
        onResult: function (results) {
            var typedValue = $('#token-input-id_new_location').val();
            var r = [{id: typedValue, name: typedValue + ' (new)'}];
            //var r = [];
            $.each(results.data, function (i, item) {
                r.push({id: item.id, name: (item.postcode) ? 
                    (item.postcode + ', ' + item.place_name) : 
                    (item.place_name + ', ' + item.district)});
            });
            return r;
        },
        prePopulate: [{% for l in object.locations %}{id: '{{ l.id }}', name: '{{ l }}'}{% if not forloop.last %},{% endif %}{% endfor %}],
        queryParam: 'match',
        theme: 'aliss'
    });
{% endif %}
{% endblock document-ready %}

engineclub/apps/engine/resources/templates/depot/resource_find.html
{% extends "depot/resource_base.html" %}

{% load utils accounts_tags depot_tags markup %}
{% load url from future %}

{% block title %}find resources{% endblock %}

{% block body_class %}search resource{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumbs">
  <li class="current"><a href="#">Search Aliss resources</a></li>
</ul>
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<dl class="sub-nav">
  <dt>Actions:</dt>
  <dd><a href="{% url 'resource_add' %}">Add a new resource</a></dd>
  <dd><a href="{% url 'accounts_detail' user|account_id %}">Browse your curations</a></dd>
  {% if user.is_staff %}
    <dd><a href="{% url 'cab_reindex' %}" id="reindex">Reindex resources</a></dd>
  {% endif %}
</dl>

<div id="loading">working...</div>

{% endif %}

  <h1>Search Aliss resources</h1>

  <div class="row">

    <div class="search-form{% if not show_map %}-full{% endif %}">
      <form class="nice form" action="." method="GET" id="search_form">{% csrf_token %}
        <fieldset>
          <legend><span>Type in a place, post code, or words:</span></legend>

          {{ form.as_plain }}

          <input type="submit" name="result" value="Find items" id="submit_button">
        </fieldset>
      </form>

    </div>      
  {% if show_map %}<div id="map"></div>{% endif %}
  </div>

  <div class="row results">

    <ul class="resource-listing">
      {% for resource in results %}
        {#% with result.resource_result as resource %#}

          <li>
            <div class="row">
            <h3 id="res_{{ resource.res_id }}"><a href="{% url 'resource' object_id=resource.res_id %}">{{ resource.title }}</a></h3>
            {% if resource.event_start %} 
              <p class="event">{{ resource|idx_event_start }}{% if resource.event_end %} - {{ resource|idx_event_end }}{% endif %}</p>
            {% endif %}
            <div class="location">
            {% if resource.loc_labels %}
              <h4>Location:</h4>
              {% for loc_label in resource.loc_labels %}
                <p>{{ loc_label }}</p>
              {% endfor %}
            {% endif %}
            </div>
            {{ resource.short_description|truncatewords:30|textile }}
            <p>
              {% for tag in resource.resource.all_tags %}
                <span class="white label"><a href="{{ resource.resource|search_url:tag }}">{{ tag }}</a></span>
              {% endfor %}
            </p>
            <p>{% if user.username == 'derek' %}{{resource.score}}&nbsp;&nbsp;&nbsp;&nbsp;{% endif %}
            <a href="#top" class="action top">top</a>
            {% if user.is_authenticated %}
              {% with curation=resource.resource|curation_for_user:user  %}
                {% if curation %} 
                  <!-- <a href="">edit your curation</a> -->
                {% else %}
                  | <a href="{% url 'curation_add' resource.res_id %}?next={{next}}">add to your curations </a>
                {% endif %}
              {% endwith %}
            {% endif %}</p>
            </div>
          </li>
        {#% endwith %#}
      {% empty %}
        {% if not new_search %} 
          <li>no results found for your area of interest. Would you like to <a href="{% url 'contact' %}">help us create some</a>?</li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>

{% endblock %}

{% block script-extra %}
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/base/jquery-ui.css" type="text/css" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript"></script>

<script type="text/javascript" src="http://maps.google.com/maps?file=api&v=2&key={{ google_key }}"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/mxn-min.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/mxn.core-min.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/js/mxn.google.core-min.js"></script>

{% endblock script-extra %}

{% block document-ready %}{% include 'depot/resource_find_map_js.html' with res_type='resource' rev_url='resource' %}

$( "#id_post_code" ).autocomplete({
  source: function( request, response ) {
    $.ajax({
      url: "{% url 'resources.api_handlers.locations' %}",
      dataType: "jsonp",
      data: {
        match: request.term,
        postcodes: 0
      },
      success: function( results ) {
        response( $.map( results.data, function( item ) {
          return {
            value: (item.postcode) ? 
                    (item.postcode) : 
                    (item.place_name) + ': ' + item.district
          }
        }));
      }
    });
  },
  minLength: 3
});
$( "#id_kwords" ).autocomplete({
  source: function( request, response ) {
    $.ajax({
      url: "{% url 'resources.api_handlers.tags' %}",
      dataType: "jsonp",
      data: {
        match: request.term
      },
      success: function( results ) {
        response( $.map( results.data, function( item ) {
          return {
            value: item
          }
        }));
      }
    });
  },
  minLength: 3
});

{% endblock document-ready %}

engineclub/apps/engine/resources/templates/depot/resource_find_map_js.html
{# Just needs rev_url set to work for Resource or Account #}
{% load utils depot_tags markup %}
{% load url from future %}
  {% if centres or pt_results %}
    mapstraction = new mxn.Mapstraction('map','google');
    //mapstraction = new mxn.Mapstraction('map','openlayers');

    var centre_pin;
    {% for pin in centres %}
      centre_pin =  new mxn.Marker(new mxn.LatLonPoint({{pin.location.0}}, {{pin.location.1}}))
      centre_pin.setIcon("/static/images/misc/blue-pin.png", [21,34], [10,34]);
      centre_pin.setShadowIcon('/static/images/misc/pin-shadow50.png')     
      mapstraction.addMarker(centre_pin);      
    {% endfor %}

    {% for loc, res_objs in pt_results.items %}
        advancedMarker({{ loc.0 }}, {{ loc.1 }}, '{% for id, title in res_objs %}<p><a href="{% url rev_url id %}">{{ title }}</a></p>{% endfor %}');
    {% endfor %}

    function advancedMarker(lat, lon, info) {
      mapstraction.addMarkerWithData(new mxn.Marker( new mxn.LatLonPoint(lat, lon)),{
        infoBubble : info,
        label : "",
        // marker : 3,
        icon : "/static/images/misc/ymarker_or.png",
        iconSize : [25,25],
        iconAnchor: [0,25],
        draggable : false,
        hover : true
      });
    };

    mapstraction.addControls({
      pan: true, 
      zoom: 'small',
      map_type: true 
    });
    
    mapstraction.autoCenterAndZoom();
    {% if pt_results|length < 2 and centres|length < 2 %} 
      mapstraction.setZoom(12);
    {% endif %}

  {% endif %}
  $('.sub-nav a').click(function() {
    $('#loading').show();
  })

engineclub/apps/engine/resources/templates/depot/resource_popup_cancel.html
{% extends "base_popup.html" %}

{% block title %}resource cancelled{% endblock %}

{% block body_extra %}onLoad="setTimeout('self.close()',1000)"{% endblock body_extra %}
{% block content %}
<h1>Cancelled</h1>

<p>The item was not added.</p>

<p><a href="javascript:window.close();">close this window</a></p>
{% endblock %}